#include "FractalRegistry.h"
#include "MandelbrotCalculator.h"
#include <cmath>
#include <vector>

namespace Native {

//=============================================================================
// IFS (Iterated Function Systems) Family
// Fractals generated by iterating through sets of affine transformations
//=============================================================================

void RegisterIFSFamily()
{
    FractalSpec spec;

    //=========================================================================
    // Barnsley Fern IFS
    //=========================================================================
    spec.name = "BarnsleyFern";
    spec.displayName = "Barnsley Fern (IFS)";
    spec.category = "IFS";
    spec.type = FractalCategory::Special;
    spec.description = "Classic Barnsley fern generated using an iterated function system";
    spec.formula = "IFS with 4 transformations and weighted probabilities";
    spec.formulaLatex = R"(x_{n+1}, y_{n+1} = f_i(x_n, y_n) \text{ where } i \text{ is chosen by probability})";

    spec.calculator = [](ComplexD c, int maxIter, bool isJulia, ComplexD juliaC, const ParamMap& params) -> double {
        // Map pixel coordinates to IFS iteration starting point
        double x = c.real;
        double y = c.imag;

        // Run IFS iterations
        for (int i = 0; i < maxIter; ++i)
        {
            // Use deterministic function selection based on position
            double selector = std::fmod(x * y * 1000.0, 1.0);

            double newX, newY;
            if (selector < 0.01)  // Stem (1%)
            {
                newX = 0.0;
                newY = 0.16 * y;
            }
            else if (selector < 0.86)  // Smaller leaflets (85%)
            {
                newX = 0.85 * x + 0.04 * y;
                newY = -0.04 * x + 0.85 * y + 1.6;
            }
            else if (selector < 0.93)  // Largest left leaflet (7%)
            {
                newX = 0.2 * x - 0.26 * y;
                newY = 0.23 * x + 0.22 * y + 1.6;
            }
            else  // Largest right leaflet (7%)
            {
                newX = -0.15 * x + 0.28 * y;
                newY = 0.26 * x + 0.24 * y + 0.44;
            }

            x = newX;
            y = newY;
        }

        // Return distance from final point to pixel
        double dist = std::sqrt((x - c.real) * (x - c.real) + (y - c.imag) * (y - c.imag));
        return maxIter * (1.0 - std::min(1.0, dist));
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.0;
    spec.defaultCenterY = 5.0;
    spec.defaultZoom = 0.1;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = false;

    FractalRegistry::Register(spec);

    //=========================================================================
    // Sierpinski Triangle IFS
    //=========================================================================
    spec.name = "SierpinskiIFS";
    spec.displayName = "Sierpinski Triangle (IFS)";
    spec.category = "IFS";
    spec.type = FractalCategory::Special;
    spec.description = "Sierpinski triangle generated using chaos game IFS method";
    spec.formula = "IFS: pick random vertex, move halfway to it, plot point";
    spec.formulaLatex = R"(p_{n+1} = \frac{p_n + v_i}{2} \text{ where } v_i \text{ is a random vertex})";

    spec.calculator = [](ComplexD c, int maxIter, bool isJulia, ComplexD juliaC, const ParamMap& params) -> double {
        // Three vertices of equilateral triangle
        double v1x = 0.0, v1y = 0.0;
        double v2x = 1.0, v2y = 0.0;
        double v3x = 0.5, v3y = 0.866025;  // sqrt(3)/2

        double x = c.real;
        double y = c.imag;

        // Run chaos game iterations
        for (int i = 0; i < maxIter; ++i)
        {
            // Choose vertex deterministically based on current position
            double selector = std::fmod(x * y * 12345.67, 3.0);

            if (selector < 1.0)
            {
                x = (x + v1x) * 0.5;
                y = (y + v1y) * 0.5;
            }
            else if (selector < 2.0)
            {
                x = (x + v2x) * 0.5;
                y = (y + v2y) * 0.5;
            }
            else
            {
                x = (x + v3x) * 0.5;
                y = (y + v3y) * 0.5;
            }
        }

        // Return distance from final point to pixel
        double dist = std::sqrt((x - c.real) * (x - c.real) + (y - c.imag) * (y - c.imag));
        return maxIter * (1.0 - std::min(1.0, dist * 10.0));
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.5;
    spec.defaultCenterY = 0.433;
    spec.defaultZoom = 1.5;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = true;

    FractalRegistry::Register(spec);

    //=========================================================================
    // Dragon Curve IFS
    //=========================================================================
    spec.name = "DragonCurveIFS";
    spec.displayName = "Dragon Curve (IFS)";
    spec.category = "IFS";
    spec.type = FractalCategory::Special;
    spec.description = "Heighway dragon curve generated using IFS";
    spec.formula = "IFS with two transformations creating self-similar dragon pattern";
    spec.formulaLatex = R"(f_1(x,y) = \frac{1}{\sqrt{2}}(x - y, x + y), \; f_2(x,y) = \frac{1}{\sqrt{2}}(y - x + 1, -x - y + 1))";

    spec.calculator = [](ComplexD c, int maxIter, bool isJulia, ComplexD juliaC, const ParamMap& params) -> double {
        double x = c.real;
        double y = c.imag;
        const double scale = 1.0 / 1.414213562;  // 1/sqrt(2)

        for (int i = 0; i < maxIter; ++i)
        {
            double selector = std::fmod(x * y * 54321.0, 2.0);

            double newX, newY;
            if (selector < 1.0)
            {
                // First transformation
                newX = scale * (x - y);
                newY = scale * (x + y);
            }
            else
            {
                // Second transformation
                newX = scale * (y - x) + 1.0;
                newY = scale * (-x - y) + 1.0;
            }

            x = newX;
            y = newY;
        }

        double dist = std::sqrt((x - c.real) * (x - c.real) + (y - c.imag) * (y - c.imag));
        return maxIter * (1.0 - std::min(1.0, dist * 5.0));
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.5;
    spec.defaultCenterY = 0.5;
    spec.defaultZoom = 1.2;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = false;

    FractalRegistry::Register(spec);

    //=========================================================================
    // Pentagon IFS
    //=========================================================================
    spec.name = "PentagonIFS";
    spec.displayName = "Pentagon (IFS)";
    spec.category = "IFS";
    spec.type = FractalCategory::Special;
    spec.description = "Pentagonal fractal generated using chaos game with 5 vertices";
    spec.formula = "IFS: choose random pentagon vertex, move 5/8 toward it";
    spec.formulaLatex = R"(p_{n+1} = \frac{3p_n + 5v_i}{8})";

    spec.calculator = [](ComplexD c, int maxIter, bool isJulia, ComplexD juliaC, const ParamMap& params) -> double {
        // Five vertices of regular pentagon
        const double pi = 3.14159265358979323846;
        std::vector<double> vx(5), vy(5);
        for (int i = 0; i < 5; ++i)
        {
            double angle = 2.0 * pi * i / 5.0 - pi / 2.0;
            vx[i] = std::cos(angle);
            vy[i] = std::sin(angle);
        }

        double x = c.real;
        double y = c.imag;

        for (int i = 0; i < maxIter; ++i)
        {
            int vertexIdx = (int)std::fmod(std::abs(x * y * 99999.0), 5.0);
            x = (3.0 * x + 5.0 * vx[vertexIdx]) / 8.0;
            y = (3.0 * y + 5.0 * vy[vertexIdx]) / 8.0;
        }

        double dist = std::sqrt((x - c.real) * (x - c.real) + (y - c.imag) * (y - c.imag));
        return maxIter * (1.0 - std::min(1.0, dist * 8.0));
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.0;
    spec.defaultCenterY = 0.0;
    spec.defaultZoom = 1.5;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = true;

    FractalRegistry::Register(spec);

    //=========================================================================
    // Tree IFS
    //=========================================================================
    spec.name = "TreeIFS";
    spec.displayName = "Tree (IFS)";
    spec.category = "IFS";
    spec.type = FractalCategory::Special;
    spec.description = "Fractal tree generated using branching IFS";
    spec.formula = "IFS with branching transformations creating tree structure";
    spec.formulaLatex = R"(\text{Branch left/right with rotation and scaling})";

    spec.calculator = [](ComplexD c, int maxIter, bool isJulia, ComplexD juliaC, const ParamMap& params) -> double {
        double x = c.real;
        double y = c.imag;
        const double angle = 0.4;  // Branch angle
        const double scale = 0.65;  // Branch scale factor

        for (int i = 0; i < maxIter; ++i)
        {
            double selector = std::fmod(x * y * 77777.0, 2.0);

            double newX, newY;
            if (selector < 1.0)
            {
                // Left branch
                newX = scale * (x * std::cos(angle) - y * std::sin(angle));
                newY = scale * (x * std::sin(angle) + y * std::cos(angle)) + 0.5;
            }
            else
            {
                // Right branch
                newX = scale * (x * std::cos(-angle) - y * std::sin(-angle));
                newY = scale * (x * std::sin(-angle) + y * std::cos(-angle)) + 0.5;
            }

            x = newX;
            y = newY;
        }

        double dist = std::sqrt((x - c.real) * (x - c.real) + (y - c.imag) * (y - c.imag));
        return maxIter * (1.0 - std::min(1.0, dist * 3.0));
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.0;
    spec.defaultCenterY = 2.0;
    spec.defaultZoom = 0.3;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = false;

    FractalRegistry::Register(spec);
}

} // namespace Native
