#include "FractalRegistry.h"
#include "MandelbrotCalculator.h"
#include <cmath>
#include <vector>

namespace Native {

//=============================================================================
// IFS (Iterated Function Systems) Family
// Fractals generated by iterating through sets of affine transformations
//=============================================================================

void RegisterIFSFamily()
{
    FractalSpec spec;

    //=========================================================================
    // Barnsley Fern IFS
    //=========================================================================
    spec.name = "BarnsleyFern";
    spec.displayName = "Barnsley Fern (IFS)";
    spec.category = "Iterated Function Systems";
    spec.type = FractalCategory::HistogramBased;
    spec.description = "Classic Barnsley fern generated using an iterated function system";
    spec.formula = "IFS with 4 transformations and weighted probabilities";
    spec.formulaLatex = R"(x_{n+1}, y_{n+1} = f_i(x_n, y_n) \text{ where } i \text{ is chosen by probability})";

    // Orbit iterator for histogram-based rendering
    spec.orbitIterator = [](double& x, double& y, double& z, const ParamMap& params) {
        // Static seed that evolves but resets each render via z parameter
        static unsigned int seed = 12345u;

        // Reset seed at start of render (when z is very small, like iteration 0-1)
        if (z < 2.0) {
            seed = 12345u;
        }

        seed = (seed * 1103515245u + 12345u) & 0x7fffffffu;
        double selector = static_cast<double>(seed) / 2147483648.0;

        double newX, newY;
        if (selector < 0.01)  // Stem (1%)
        {
            newX = 0.0;
            newY = 0.16 * y;
        }
        else if (selector < 0.86)  // Successively smaller leaflets (85%)
        {
            newX = 0.85 * x + 0.04 * y;
            newY = -0.04 * x + 0.85 * y + 1.6;
        }
        else if (selector < 0.93)  // Largest left-hand leaflet (7%)
        {
            newX = 0.2 * x - 0.26 * y;
            newY = 0.23 * x + 0.22 * y + 1.6;
        }
        else  // Largest right-hand leaflet (7%)
        {
            newX = -0.15 * x + 0.28 * y;
            newY = 0.26 * x + 0.24 * y + 0.44;
        }

        x = newX;
        y = newY;
        // z used for seed reset detection
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.0;
    spec.defaultCenterY = 5.0;
    spec.defaultZoom = 0.1;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = false;

    FractalRegistry::Register(spec);

    //=========================================================================
    // Sierpinski Triangle IFS
    //=========================================================================
    spec.name = "SierpinskiIFS";
    spec.displayName = "Sierpinski Triangle (IFS)";
    spec.category = "Iterated Function Systems";
    spec.type = FractalCategory::HistogramBased;
    spec.description = "Sierpinski triangle generated using chaos game IFS method";
    spec.formula = "IFS: pick random vertex, move halfway to it, plot point";
    spec.formulaLatex = R"(p_{n+1} = \frac{p_n + v_i}{2} \text{ where } v_i \text{ is a random vertex})";

    spec.orbitIterator = [](double& x, double& y, double& z, const ParamMap& params) {
        // Three vertices of equilateral triangle
        const double v1x = 0.0, v1y = 0.0;
        const double v2x = 1.0, v2y = 0.0;
        const double v3x = 0.5, v3y = 0.866025;  // sqrt(3)/2

        static unsigned int seed = 54321u;

        // Reset seed at start of render
        if (z < 2.0) {
            seed = 54321u;
        }

        seed = (seed * 1103515245u + 12345u) & 0x7fffffffu;
        double selector = static_cast<double>(seed) / 2147483648.0 * 3.0;

        if (selector < 1.0)
        {
            x = (x + v1x) * 0.5;
            y = (y + v1y) * 0.5;
        }
        else if (selector < 2.0)
        {
            x = (x + v2x) * 0.5;
            y = (y + v2y) * 0.5;
        }
        else
        {
            x = (x + v3x) * 0.5;
            y = (y + v3y) * 0.5;
        }
        // z used for seed reset detection
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.5;
    spec.defaultCenterY = 0.433;
    spec.defaultZoom = 1.5;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = true;

    FractalRegistry::Register(spec);

    //=========================================================================
    // Dragon Curve IFS
    //=========================================================================
    spec.name = "DragonCurveIFS";
    spec.displayName = "Dragon Curve (IFS)";
    spec.category = "Iterated Function Systems";
    spec.type = FractalCategory::HistogramBased;
    spec.description = "Heighway dragon curve generated using IFS";
    spec.formula = "IFS with two transformations creating self-similar dragon pattern";
    spec.formulaLatex = R"(f_1(x,y) = \frac{1}{\sqrt{2}}(x - y, x + y), \; f_2(x,y) = \frac{1}{\sqrt{2}}(y - x + 1, -x - y + 1))";

    spec.orbitIterator = [](double& x, double& y, double& z, const ParamMap& params) {
        // Heighway Dragon IFS - Alternative formulation with 1/(√2)² = 0.5 coefficients
        // This creates the characteristic dragon fold pattern

        static unsigned int seed = 98765u;

        // Reset seed at start of render
        if (z < 2.0) {
            seed = 98765u;
        }

        seed = (seed * 1103515245u + 12345u) & 0x7fffffffu;
        double selector = static_cast<double>(seed) / 2147483648.0;

        double newX, newY;
        if (selector < 0.5)
        {
            // f1: contracts and rotates 45°
            // Matrix form: scale * [ cos(π/4) -sin(π/4) ]  = [ 0.5  -0.5 ]
            //                      [ sin(π/4)  cos(π/4) ]    [ 0.5   0.5 ]
            newX = 0.5 * (x - y);
            newY = 0.5 * (x + y);
        }
        else
        {
            // f2: contracts, rotates -135°, and translates by (1,0)
            // This creates the reflection/fold
            newX = 0.5 * (-x - y) + 1.0;
            newY = 0.5 * (x - y);
        }

        x = newX;
        y = newY;
        // z used for seed reset detection
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.5;
    spec.defaultCenterY = 0.0;
    spec.defaultZoom = 2.0;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = false;

    FractalRegistry::Register(spec);

    //=========================================================================
    // Pentagon IFS
    //=========================================================================
    spec.name = "PentagonIFS";
    spec.displayName = "Pentagon (IFS)";
    spec.category = "Iterated Function Systems";
    spec.type = FractalCategory::HistogramBased;
    spec.description = "Pentagonal fractal generated using chaos game with 5 vertices";
    spec.formula = "IFS: choose random pentagon vertex, move 5/8 toward it";
    spec.formulaLatex = R"(p_{n+1} = \frac{3p_n + 5v_i}{8})";

    spec.orbitIterator = [](double& x, double& y, double& z, const ParamMap& params) {
        // Five vertices of regular pentagon
        static const double pi = 3.14159265358979323846;
        static const double vx[5] = {
            std::cos(2.0 * pi * 0 / 5.0 - pi / 2.0),
            std::cos(2.0 * pi * 1 / 5.0 - pi / 2.0),
            std::cos(2.0 * pi * 2 / 5.0 - pi / 2.0),
            std::cos(2.0 * pi * 3 / 5.0 - pi / 2.0),
            std::cos(2.0 * pi * 4 / 5.0 - pi / 2.0)
        };
        static const double vy[5] = {
            std::sin(2.0 * pi * 0 / 5.0 - pi / 2.0),
            std::sin(2.0 * pi * 1 / 5.0 - pi / 2.0),
            std::sin(2.0 * pi * 2 / 5.0 - pi / 2.0),
            std::sin(2.0 * pi * 3 / 5.0 - pi / 2.0),
            std::sin(2.0 * pi * 4 / 5.0 - pi / 2.0)
        };

        static unsigned int seed = 11111u;

        // Reset seed at start of render
        if (z < 2.0) {
            seed = 11111u;
        }

        seed = (seed * 1103515245u + 12345u) & 0x7fffffffu;
        int vertexIdx = (int)((seed / 2147483648.0) * 5.0) % 5;

        x = (3.0 * x + 5.0 * vx[vertexIdx]) / 8.0;
        y = (3.0 * y + 5.0 * vy[vertexIdx]) / 8.0;
        // z unused
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.0;
    spec.defaultCenterY = 0.0;
    spec.defaultZoom = 1.5;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = true;

    FractalRegistry::Register(spec);

    //=========================================================================
    // Tree IFS
    //=========================================================================
    spec.name = "TreeIFS";
    spec.displayName = "Tree (IFS)";
    spec.category = "Iterated Function Systems";
    spec.type = FractalCategory::HistogramBased;
    spec.description = "Fractal tree generated using branching IFS";
    spec.formula = "IFS with branching transformations creating tree structure";
    spec.formulaLatex = R"(\text{Branch left/right with rotation and scaling})";

    spec.orbitIterator = [](double& x, double& y, double& z, const ParamMap& params) {
        const double angle = 0.4;  // Branch angle
        const double scale = 0.65;  // Branch scale factor

        static unsigned int seed = 22222u;

        // Reset seed at start of render
        if (z < 2.0) {
            seed = 22222u;
        }

        seed = (seed * 1103515245u + 12345u) & 0x7fffffffu;
        double selector = static_cast<double>(seed) / 2147483648.0;

        double newX, newY;
        if (selector < 0.5)
        {
            // Left branch
            newX = scale * (x * std::cos(angle) - y * std::sin(angle));
            newY = scale * (x * std::sin(angle) + y * std::cos(angle)) + 0.5;
        }
        else
        {
            // Right branch
            newX = scale * (x * std::cos(-angle) - y * std::sin(-angle));
            newY = scale * (x * std::sin(-angle) + y * std::cos(-angle)) + 0.5;
        }

        x = newX;
        y = newY;
        // z unused
    };

    spec.supportsJulia = false;
    spec.defaultCenterX = 0.0;
    spec.defaultCenterY = 2.0;
    spec.defaultZoom = 0.3;
    spec.defaultBailout = 256.0;
    spec.hasSymmetry = false;

    FractalRegistry::Register(spec);
}

} // namespace Native
